kafka:
  topics:
    raw_frames:
      name: "raw_video_frames_s2"
      partitions: 4
    processed_tracklets:
      name: "processed_tracklets"
      partitions: 4
    final_results:
      name: "final_results"
      partitions: 1

  topic_creation:
    replication_factor: 3

  topic_test:
    name: "test_c06"

producer:
  video_source_dir: "datasets/aic_2022/videos/S02"
  cameras_to_stream: ["c007"]
  frame_rate_limit: 10 # Every camera have 10 FPS / s (8FPS) --> FPS
